name: test-wf2

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop", "feature-createchange"]
 # Allows you to run this workflow manually from the Actions tab 
  workflow_dispatch:
jobs:
  call-workflow-passing-data:
   uses: ./.github/workflows/projectrepo..yml
   with:
        java-version: '17'
        distribution: 'temurin'
  publish-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: mvn --batch-mode --update-snapshots verify
    - run: mvn test
    - run: mkdir staging && cp target/*.jar staging && cp target/surefire-reports/*.xml staging && cp target/surefire-reports/TEST-hello.GreeterTest.xml target/surefire-reports/testng-results.xml
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging
